credentials:
  usernames:
   luxem:  # tu usuario (puedes poner el que quieras)
      email: luis.soliz@teamleading-cpm.com
      name: Luis Soliz
      password: luxem   # ¡cámbiala por una real y segura!

cookie:
  expiry_days: 30
  key: alguna_clave_secreta_larga_y_random   # pon algo como "supersecreto123xyz" (cualquier string único)
  name: cogeneracion_cookie


